from __future__ import annotations

import argparse
import re
from collections.abc import Sequence

# The ``BuildSystem: pyproject`` spec files of the openRuyi project must
# follow the pyproject build system guidelines
# (https://www.openruyi.cn/zh-Hans/docs/guide/packaging-guidelines/BuildSystems/pyproject):
#
#   Dependencies:
#     "When using the pyproject build system, at least these
#      BuildRequires are usually needed":
#
#         BuildRequires:  pyproject-rpm-macros
#         BuildRequires:  pkgconfig(python3)
#
#   Examples:
#     "When using the pyproject declarative build system, the module
#      name must be passed to BuildOption(install)" (the option is
#      forwarded to %pyproject_save_files).
#
#   Testing:
#     "Modules may be excluded through BuildOption(check), and the
#      reason must be written in a comment above."
#
# Statically checkable rules in this hook (applied only when
# ``BuildSystem`` is ``pyproject``):
#   * the header ``BuildRequires`` must declare ``pyproject-rpm-macros``;
#   * a ``BuildOption(install)`` must carry a module name (a non-empty
#     argument list);
#   * each ``BuildOption(check)`` block must be preceded by a comment
#     that explains why the modules are excluded.
#
# Not checked here:
#   * ``pkgconfig(python3)``: the guideline phrases it "usually needed"
#     and ``%pyproject_buildrequires`` generates it automatically, so it
#     is not a hard requirement;
#   * the ``-l`` flag of ``BuildOption(install)``: "usually
#     recommended", but conditional on the upstream PEP 639
#     License-File declaration ("if a No License-File error is reported,
#     drop the argument");
#   * ``%generate_buildrequires`` / ``%pyproject_buildrequires``: the
#     recommended way to generate dependencies, not a hard requirement;
#   * an empty ``%check``: "generally, you should not" (weak
#     guideline) and the declarative system still runs its smoke test;
#   * applicability (upstream ``pyproject.toml`` + PEP 517): depends on
#     the upstream source tree and cannot be judged from the spec alone.
#
# Field presence of ``BuildSystem`` is covered by ``check-spec-structure``;
# the general two-space/order rules of ``BuildOption`` are covered by
# ``check-spec-buildoption``.

_RE_BUILDSYSTEM = re.compile(r'^BuildSystem\s*:\s*(.*)')
_RE_BUILDREQUIRES = re.compile(r'^BuildRequires\s*:\s*(.*)')
_RE_BUILDOPTION = re.compile(r'^BuildOption\s*\(([^)]*)\)\s*:(.*)')

# The dependency every pyproject spec must declare (the other guideline
# BuildRequire, ``pkgconfig(python3)``, is auto-generated by
# ``%pyproject_buildrequires`` so it is not a hard requirement).
_REQUIRED_BUILDREQUIRES = frozenset({'pyproject-rpm-macros'})

_PYPROJECT_BUILDSYSTEM = 'pyproject'

# See check_spec_perl._dependencies_in_values: ``-`` is a valid
# package-name character (e.g. ``pyproject-rpm-macros``), so it is kept,
# but a bare ``-suffix`` left over from a stripped macro must not count.
_TOKEN_RE = re.compile(r'^[A-Za-z0-9_.+/]+(?:-[A-Za-z0-9_.+/]+)*$')
_MACRO_RE = re.compile(r'%\{[^}]*\}')
_BARE_MACRO_RE = re.compile(
    r'(?<![A-Za-z0-9_.-])%[A-Za-z_][A-Za-z0-9_]*(?![A-Za-z0-9_.])',
)


def _dependencies_in_values(values: list[str]) -> set[str]:
    """Extract the set of dependency names from ``BuildRequires`` values.

    Values are read from the raw ``BuildRequires:`` lines.  A value can
    declare several packages (the general rule of one dependency per
    line is enforced by ``check-spec-buildrequires``), so every token is
    collected here.
    """
    deps: set[str] = set()
    for value in values:
        # strip rpm macros so ``%{?foo}-devel`` does not pollute the set
        value = _MACRO_RE.sub(' ', value)
        value = _BARE_MACRO_RE.sub(' ', value)
        for token in re.split(r'[\s,()]', value):
            token = token.strip()
            if _TOKEN_RE.match(token):
                deps.add(token)
    return deps


def _previous_nonblank(lines: list[str], index: int) -> int:
    """Return the index of the nearest non-blank line before ``index``.

    ``-1`` when no such line exists.
    """
    j = index - 1
    while j >= 0 and not lines[j].strip():
        j -= 1
    return j


def _is_check_block_start(lines: list[str], index: int) -> bool:
    """Whether ``lines[index]`` starts a ``BuildOption(check)`` block.

    Consecurive ``BuildOption(check)`` lines (no blank lines in
    between) form one block; only its first line needs the comment.
    """
    j = _previous_nonblank(lines, index)
    if j < 0:
        return True
    m = _RE_BUILDOPTION.match(lines[j].strip())
    if m and m.group(1).strip() == 'check':
        return False
    return True


def _has_comment_above(lines: list[str], index: int) -> bool:
    """Whether the nearest non-blank line above ``index`` is a comment."""
    j = _previous_nonblank(lines, index)
    return j >= 0 and lines[j].strip().startswith('#')


def _check_spec_pyproject(filename: str) -> list[str]:
    """Validate the pyproject build requirements of ``filename``.

    Returns a list of human readable error messages; empty on success.
    """
    errors: list[str] = []
    try:
        with open(filename, encoding='utf-8') as f:
            lines = f.read().splitlines()
    except UnicodeDecodeError:
        return [f'{filename}: file is not valid UTF-8']
    except OSError as exc:
        return [f'{filename}: {exc}']

    if not lines:
        return [f'{filename}: file is empty']

    # Only the header region is inspected: ``BuildRequires`` inside a
    # ``%package`` subpackage block declares the subpackage build
    # dependencies and is not covered by this rule.
    cut = len(lines)
    for i, line in enumerate(lines):
        if re.match(r'^%(?:description|package)\b', line.strip()):
            cut = i
            break

    buildsystem_value: str | None = None
    buildrequires: list[str] = []
    install_options: list[tuple[int, str]] = []
    check_indices: list[int] = []
    for i, line in enumerate(lines[:cut]):
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if buildsystem_value is None:
            m = _RE_BUILDSYSTEM.match(stripped)
            if m:
                buildsystem_value = m.group(1).strip()
        m = _RE_BUILDREQUIRES.match(stripped)
        if m:
            buildrequires.append(m.group(1).strip())
        m = _RE_BUILDOPTION.match(stripped)
        if m:
            stage = m.group(1).strip()
            value = m.group(2).strip()
            if stage == 'install':
                install_options.append((i + 1, value))
            elif stage == 'check':
                check_indices.append(i)

    if buildsystem_value != _PYPROJECT_BUILDSYSTEM:
        # This hook only applies to pyproject specs.
        return errors

    deps = _dependencies_in_values(buildrequires)
    missing = sorted(_REQUIRED_BUILDREQUIRES - deps)
    if missing:
        errors.append(
            f'{filename}: BuildSystem is pyproject; BuildRequires must '
            f'declare {", ".join(missing)}',
        )

    for lineno, value in install_options:
        if not value:
            errors.append(
                f'{filename}:{lineno}: BuildOption(install) must carry '
                f'a module name (found an empty value)',
            )

    for index in check_indices:
        if (
            _is_check_block_start(lines, index) and
            not _has_comment_above(lines, index)
        ):
            errors.append(
                f'{filename}:{index + 1}: BuildOption(check) must be '
                f'preceded by a comment explaining why the modules are '
                f'skipped',
            )
    return errors


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames', nargs='*', help='spec files to check')
    args = parser.parse_args(argv)

    retv = 0
    for filename in args.filenames:
        for err in _check_spec_pyproject(filename):
            print(err)
            retv = 1
    return retv


if __name__ == '__main__':
    raise SystemExit(main())
