-   id: check-ast
    name: check python ast
    description: simply checks whether the files parse as valid python.
    entry: check-ast
    language: python
    types: [python]
-   id: check-executables-have-shebangs
    name: check that executables have shebangs
    description: ensures that (non-binary) executables have a shebang.
    entry: check-executables-have-shebangs
    language: python
    types: [text, executable]
-   id: check-yaml
    name: check yaml
    description: checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
-   id: require-ascii
    name: require ascii
    description: ensures that files contain only ascii characters.
    entry: require-ascii
    language: python
    types: [text]
-   id: trailing-whitespace
    name: trim trailing whitespace
    description: trims trailing whitespace.
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
