[metadata]
name = openruyi-precommit-hooks
version = 0.1.0
description = Some out-of-the-box hooks for pre-commit (openruyi edition).
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/redrose2100/openruyi-precommit-hooks
author = redrose2100
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython

[options]
packages = find:
install_requires =
    pyyaml>=6.0
python_requires = >=3.10

[options.packages.find]
exclude =
    tests*
    testing*

[options.entry_points]
console_scripts =
    check-spdx-header = openruyi_precommit_hooks.check_spdx_header:main
    check-spec-structure = openruyi_precommit_hooks.check_spec_structure:main
    check-spec-name = openruyi_precommit_hooks.check_spec_name:main
    check-spec-version = openruyi_precommit_hooks.check_spec_version:main
    check-spec-release = openruyi_precommit_hooks.check_spec_release:main
    check-spec-summary = openruyi_precommit_hooks.check_spec_summary:main
    check-spec-license = openruyi_precommit_hooks.check_spec_license:main
    check-spec-url = openruyi_precommit_hooks.check_spec_url:main
    check-spec-source = openruyi_precommit_hooks.check_spec_source:main
    check-spec-vcs = openruyi_precommit_hooks.check_spec_vcs:main
    check-spec-buildarch = openruyi_precommit_hooks.check_spec_buildarch:main
    check-spec-buildsystem = openruyi_precommit_hooks.check_spec_buildsystem:main
    check-spec-buildoption = openruyi_precommit_hooks.check_spec_buildoption:main
    check-spec-patch = openruyi_precommit_hooks.check_spec_patch:main

[bdist_wheel]
universal = True

[mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[mypy-testing.*]
disallow_untyped_defs = false

[mypy-tests.*]
disallow_untyped_defs = false
