# flake8: noqa: E501  -- spec file contents are reproduced verbatim
from __future__ import annotations

from pathlib import Path

from openruyi_precommit_hooks.check_spdx_header import main

GOOD_HEADER_WITH_CONTRIBUTOR = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Your Name <your.email@example.com>
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
Version:        1.0
'''

GOOD_HEADER_WITHOUT_CONTRIBUTOR = '''\
# SPDX-FileCopyrightText: (C) 2025, 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025, 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''

GOOD_HEADER_YEAR_RANGE = '''\
# SPDX-FileCopyrightText: (C) 2025-2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025-2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''


def _write(tmp_path: Path, name: str, content: str) -> str:
    p = tmp_path / name
    p.write_text(content, encoding='utf-8')
    return str(p)


def test_ok_header_with_contributor(tmp_path: Path) -> None:
    retv = main([_write(tmp_path, 'good1.spec', GOOD_HEADER_WITH_CONTRIBUTOR)])
    assert retv == 0


def test_ok_header_without_contributor(tmp_path: Path) -> None:
    retv = main([_write(tmp_path, 'good2.spec', GOOD_HEADER_WITHOUT_CONTRIBUTOR)])
    assert retv == 0


def test_ok_header_year_range(tmp_path: Path) -> None:
    retv = main([_write(tmp_path, 'good3.spec', GOOD_HEADER_YEAR_RANGE)])
    assert retv == 0


def test_missing_iscas_copyright(tmp_path: Path) -> None:
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''
    retv = main([_write(tmp_path, 'bad1.spec', content)])
    assert retv == 1


def test_missing_openruyi_copyright(tmp_path: Path) -> None:
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''
    retv = main([_write(tmp_path, 'bad2.spec', content)])
    assert retv == 1


def test_missing_license_identifier(tmp_path: Path) -> None:
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
Name:           foo
'''
    retv = main([_write(tmp_path, 'bad3.spec', content)])
    assert retv == 1


def test_wrong_license_identifier(tmp_path: Path) -> None:
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MIT
Name:           foo
'''
    retv = main([_write(tmp_path, 'bad4.spec', content)])
    assert retv == 1


def test_missing_blank_comment_line(tmp_path: Path) -> None:
    # The blank "#" separator between the copyright lines and the
    # license identifier is mandatory.
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''
    retv = main([_write(tmp_path, 'bad7.spec', content)])
    assert retv == 1


def test_too_many_blank_comment_lines(tmp_path: Path) -> None:
    # Only one blank "#" comment line is allowed between the copyright
    # lines and the license identifier.
    content = '''\
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''
    retv = main([_write(tmp_path, 'bad8.spec', content)])
    assert retv == 1


def test_no_comments_at_start(tmp_path: Path) -> None:
    content = '''\
Name:           foo
Version:        1.0
'''
    retv = main([_write(tmp_path, 'bad5.spec', content)])
    assert retv == 1


def test_empty_file(tmp_path: Path) -> None:
    retv = main([_write(tmp_path, 'bad6.spec', '')])
    assert retv == 1


def test_plain_comment_before_spdx_block(tmp_path: Path) -> None:
    # The SPDX block must be present at the start of the file, but other
    # leading comments are harmless as long as the block itself is there.
    content = '''\
# generated by openruyi-tooling
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           foo
'''
    retv = main([_write(tmp_path, 'ok3.spec', content)])
    assert retv == 0


def test_multiple_files_all_bad(tmp_path: Path) -> None:
    retv = main([
        _write(tmp_path, 'x1.spec', 'Name: a\n'),
        _write(tmp_path, 'x2.spec', 'Name: b\n'),
    ])
    assert retv == 1
